// GENERATED by scripts/gen-theme.ts — do not edit by hand.
export type ThemeMeta = { id: string; name: string };

export const DEFAULT_THEME_ID = "teams";

export const THEME_LIST: ThemeMeta[] = [
  {
    "id": "teams",
    "name": "Teams"
  },
  {
    "id": "aura",
    "name": "Aura"
  },
  {
    "id": "ayu",
    "name": "Ayu"
  },
  {
    "id": "carbonfox",
    "name": "Carbonfox"
  },
  {
    "id": "catppuccin",
    "name": "Catppuccin"
  },
  {
    "id": "catppuccin-frappe",
    "name": "Catppuccin Frappé"
  },
  {
    "id": "catppuccin-macchiato",
    "name": "Catppuccin Macchiato"
  },
  {
    "id": "cobalt2",
    "name": "Cobalt2"
  },
  {
    "id": "cursor",
    "name": "Cursor"
  },
  {
    "id": "dracula",
    "name": "Dracula"
  },
  {
    "id": "everforest",
    "name": "Everforest"
  },
  {
    "id": "flexoki",
    "name": "Flexoki"
  },
  {
    "id": "github",
    "name": "GitHub"
  },
  {
    "id": "gruvbox",
    "name": "Gruvbox"
  },
  {
    "id": "kanagawa",
    "name": "Kanagawa"
  },
  {
    "id": "lucent-orng",
    "name": "Lucent Orange"
  },
  {
    "id": "material",
    "name": "Material"
  },
  {
    "id": "matrix",
    "name": "Matrix"
  },
  {
    "id": "mercury",
    "name": "Mercury"
  },
  {
    "id": "monokai",
    "name": "Monokai"
  },
  {
    "id": "nightowl",
    "name": "Night Owl"
  },
  {
    "id": "nord",
    "name": "Nord"
  },
  {
    "id": "one-dark",
    "name": "One Dark"
  },
  {
    "id": "opencode",
    "name": "OpenCode"
  },
  {
    "id": "orng",
    "name": "Orange"
  },
  {
    "id": "osaka-jade",
    "name": "Osaka Jade"
  },
  {
    "id": "palenight",
    "name": "Palenight"
  },
  {
    "id": "rosepine",
    "name": "Rosé Pine"
  },
  {
    "id": "solarized",
    "name": "Solarized"
  },
  {
    "id": "synthwave84",
    "name": "Synthwave '84"
  },
  {
    "id": "tokyonight",
    "name": "Tokyo Night"
  },
  {
    "id": "vercel",
    "name": "Vercel"
  },
  {
    "id": "vesper",
    "name": "Vesper"
  },
  {
    "id": "zenburn",
    "name": "Zenburn"
  }
];

const IDS = new Set(THEME_LIST.map((t) => t.id));
export function isThemeId(id: string | null | undefined): id is string {
  return !!id && IDS.has(id);
}
