// Generates the static theme artifacts from the opencode theme assets:
//   - src/styles/themes.gen.css   (one [data-theme] block per theme + :root)
//   - src/lib/theme-list.gen.ts   (tiny id/name list + default, for the picker)
//
// Run via `bun run gen:theme` (wired into dev/build/test). Reading the JSON from
// disk here keeps the resolver and the 34 theme JSONs OUT of the client bundle:
// the browser only ever loads the emitted CSS and the small generated list.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildThemeEntries,
  themeList,
  themeStylesheet,
  DEFAULT_THEME_ID,
} from "../src/lib/themes.ts";
import type { ThemeJson } from "../src/lib/theme-resolve.ts";

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = join(here, "..");
const assetsDir = join(webRoot, "src", "lib", "theme-assets");

const assets: Record<string, ThemeJson> = {};
for (const file of readdirSync(assetsDir)) {
  if (!file.endsWith(".json")) continue;
  const id = file.replace(/\.json$/, "");
  assets[id] = JSON.parse(readFileSync(join(assetsDir, file), "utf8")) as ThemeJson;
}

const entries = buildThemeEntries(assets);
if (entries.length === 0) throw new Error("no themes resolved — cannot generate theme artifacts");

const css = `/* GENERATED by scripts/gen-theme.ts — do not edit by hand. */\n${themeStylesheet(entries)}\n`;
writeFileSync(join(webRoot, "src", "styles", "themes.gen.css"), css);

const list = themeList(entries);
const ts =
  `// GENERATED by scripts/gen-theme.ts — do not edit by hand.\n` +
  `export type ThemeMeta = { id: string; name: string };\n\n` +
  `export const DEFAULT_THEME_ID = ${JSON.stringify(DEFAULT_THEME_ID)};\n\n` +
  `export const THEME_LIST: ThemeMeta[] = ${JSON.stringify(list, null, 2)};\n\n` +
  `const IDS = new Set(THEME_LIST.map((t) => t.id));\n` +
  `export function isThemeId(id: string | null | undefined): id is string {\n` +
  `  return !!id && IDS.has(id);\n` +
  `}\n`;
writeFileSync(join(webRoot, "src", "lib", "theme-list.gen.ts"), ts);

console.log(`gen:theme — wrote ${entries.length} themes (default: ${DEFAULT_THEME_ID})`);
