/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppCConversationIdRouteImport } from './routes/_app.c.$conversationId'
import { Route as AppMMailIdRouteImport } from './routes/_app.m.$mailId'
import { Route as AppMrMergeRequestIdRouteImport } from './routes/_app.mr.$mergeRequestId'
import { Route as AppMrMergeRequestIdIndexRouteImport } from './routes/_app.mr.$mergeRequestId.index'
import { Route as AppMrMergeRequestIdCommitsRouteImport } from './routes/_app.mr.$mergeRequestId.commits'
import { Route as AppMrMergeRequestIdDiffRouteImport } from './routes/_app.mr.$mergeRequestId.diff'
import { Route as AppMrMergeRequestIdPipelinesRouteImport } from './routes/_app.mr.$mergeRequestId.pipelines'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCConversationIdRoute = AppCConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => AppRoute,
} as any)
const AppMMailIdRoute = AppMMailIdRouteImport.update({
  id: '/m/$mailId',
  path: '/m/$mailId',
  getParentRoute: () => AppRoute,
} as any)
const AppMrMergeRequestIdRoute = AppMrMergeRequestIdRouteImport.update({
  id: '/mr/$mergeRequestId',
  path: '/mr/$mergeRequestId',
  getParentRoute: () => AppRoute,
} as any)
const AppMrMergeRequestIdIndexRoute =
  AppMrMergeRequestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppMrMergeRequestIdRoute,
  } as any)
const AppMrMergeRequestIdCommitsRoute =
  AppMrMergeRequestIdCommitsRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => AppMrMergeRequestIdRoute,
  } as any)
const AppMrMergeRequestIdDiffRoute = AppMrMergeRequestIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => AppMrMergeRequestIdRoute,
} as any)
const AppMrMergeRequestIdPipelinesRoute =
  AppMrMergeRequestIdPipelinesRouteImport.update({
    id: '/pipelines',
    path: '/pipelines',
    getParentRoute: () => AppMrMergeRequestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRoute
  '/c/$conversationId': typeof AppCConversationIdRoute
  '/m/$mailId': typeof AppMMailIdRoute
  '/mr/$mergeRequestId': typeof AppMrMergeRequestIdRouteWithChildren
  '/mr/$mergeRequestId/commits': typeof AppMrMergeRequestIdCommitsRoute
  '/mr/$mergeRequestId/diff': typeof AppMrMergeRequestIdDiffRoute
  '/mr/$mergeRequestId/pipelines': typeof AppMrMergeRequestIdPipelinesRoute
  '/mr/$mergeRequestId/': typeof AppMrMergeRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/c/$conversationId': typeof AppCConversationIdRoute
  '/m/$mailId': typeof AppMMailIdRoute
  '/mr/$mergeRequestId/commits': typeof AppMrMergeRequestIdCommitsRoute
  '/mr/$mergeRequestId/diff': typeof AppMrMergeRequestIdDiffRoute
  '/mr/$mergeRequestId/pipelines': typeof AppMrMergeRequestIdPipelinesRoute
  '/mr/$mergeRequestId': typeof AppMrMergeRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/c/$conversationId': typeof AppCConversationIdRoute
  '/_app/m/$mailId': typeof AppMMailIdRoute
  '/_app/mr/$mergeRequestId': typeof AppMrMergeRequestIdRouteWithChildren
  '/_app/mr/$mergeRequestId/commits': typeof AppMrMergeRequestIdCommitsRoute
  '/_app/mr/$mergeRequestId/diff': typeof AppMrMergeRequestIdDiffRoute
  '/_app/mr/$mergeRequestId/pipelines': typeof AppMrMergeRequestIdPipelinesRoute
  '/_app/mr/$mergeRequestId/': typeof AppMrMergeRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/c/$conversationId'
    | '/m/$mailId'
    | '/mr/$mergeRequestId'
    | '/mr/$mergeRequestId/commits'
    | '/mr/$mergeRequestId/diff'
    | '/mr/$mergeRequestId/pipelines'
    | '/mr/$mergeRequestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/c/$conversationId'
    | '/m/$mailId'
    | '/mr/$mergeRequestId/commits'
    | '/mr/$mergeRequestId/diff'
    | '/mr/$mergeRequestId/pipelines'
    | '/mr/$mergeRequestId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_app/'
    | '/_app/c/$conversationId'
    | '/_app/m/$mailId'
    | '/_app/mr/$mergeRequestId'
    | '/_app/mr/$mergeRequestId/commits'
    | '/_app/mr/$mergeRequestId/diff'
    | '/_app/mr/$mergeRequestId/pipelines'
    | '/_app/mr/$mergeRequestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/c/$conversationId': {
      id: '/_app/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof AppCConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/m/$mailId': {
      id: '/_app/m/$mailId'
      path: '/m/$mailId'
      fullPath: '/m/$mailId'
      preLoaderRoute: typeof AppMMailIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mr/$mergeRequestId': {
      id: '/_app/mr/$mergeRequestId'
      path: '/mr/$mergeRequestId'
      fullPath: '/mr/$mergeRequestId'
      preLoaderRoute: typeof AppMrMergeRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mr/$mergeRequestId/': {
      id: '/_app/mr/$mergeRequestId/'
      path: '/'
      fullPath: '/mr/$mergeRequestId/'
      preLoaderRoute: typeof AppMrMergeRequestIdIndexRouteImport
      parentRoute: typeof AppMrMergeRequestIdRoute
    }
    '/_app/mr/$mergeRequestId/commits': {
      id: '/_app/mr/$mergeRequestId/commits'
      path: '/commits'
      fullPath: '/mr/$mergeRequestId/commits'
      preLoaderRoute: typeof AppMrMergeRequestIdCommitsRouteImport
      parentRoute: typeof AppMrMergeRequestIdRoute
    }
    '/_app/mr/$mergeRequestId/diff': {
      id: '/_app/mr/$mergeRequestId/diff'
      path: '/diff'
      fullPath: '/mr/$mergeRequestId/diff'
      preLoaderRoute: typeof AppMrMergeRequestIdDiffRouteImport
      parentRoute: typeof AppMrMergeRequestIdRoute
    }
    '/_app/mr/$mergeRequestId/pipelines': {
      id: '/_app/mr/$mergeRequestId/pipelines'
      path: '/pipelines'
      fullPath: '/mr/$mergeRequestId/pipelines'
      preLoaderRoute: typeof AppMrMergeRequestIdPipelinesRouteImport
      parentRoute: typeof AppMrMergeRequestIdRoute
    }
  }
}

interface AppMrMergeRequestIdRouteChildren {
  AppMrMergeRequestIdCommitsRoute: typeof AppMrMergeRequestIdCommitsRoute
  AppMrMergeRequestIdDiffRoute: typeof AppMrMergeRequestIdDiffRoute
  AppMrMergeRequestIdPipelinesRoute: typeof AppMrMergeRequestIdPipelinesRoute
  AppMrMergeRequestIdIndexRoute: typeof AppMrMergeRequestIdIndexRoute
}

const AppMrMergeRequestIdRouteChildren: AppMrMergeRequestIdRouteChildren = {
  AppMrMergeRequestIdCommitsRoute: AppMrMergeRequestIdCommitsRoute,
  AppMrMergeRequestIdDiffRoute: AppMrMergeRequestIdDiffRoute,
  AppMrMergeRequestIdPipelinesRoute: AppMrMergeRequestIdPipelinesRoute,
  AppMrMergeRequestIdIndexRoute: AppMrMergeRequestIdIndexRoute,
}

const AppMrMergeRequestIdRouteWithChildren =
  AppMrMergeRequestIdRoute._addFileChildren(AppMrMergeRequestIdRouteChildren)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCConversationIdRoute: typeof AppCConversationIdRoute
  AppMMailIdRoute: typeof AppMMailIdRoute
  AppMrMergeRequestIdRoute: typeof AppMrMergeRequestIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCConversationIdRoute: AppCConversationIdRoute,
  AppMMailIdRoute: AppMMailIdRoute,
  AppMrMergeRequestIdRoute: AppMrMergeRequestIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
